# Generated by Django 4.2.27 on 2026-06-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviewapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="interviewcandidate",
            new_name="interviewap_intervi_3cbddb_idx",
            old_name="interviewap_intervi_580da1_idx",
        ),
        migrations.RenameIndex(
            model_name="interviewcandidate",
            new_name="interviewap_status_7fc5cc_idx",
            old_name="interviewap_status_098b38_idx",
        ),
    ]
