# Generated by Codex on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviewapp", "0002_rename_interviewap_intervi_580da1_idx_interviewap_intervi_3cbddb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewcandidate",
            name="pan_number",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
