# Generated by Django 4.2.28 on 2026-02-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National"),
                            ("STATE", "State"),
                            ("COMPANY", "Company"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("double_pay_if_worked", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalaryIncrement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "increment_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Increment"),
                            ("promotion", "Promotion"),
                            ("performance", "Performance Based"),
                            ("adjustment", "Adjustment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "old_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "increment_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "increment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("effective_from", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="approved_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_salary_increments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="increments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Increment",
                "verbose_name_plural": "Salary Increments",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="SalaryIncrementHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="changed_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="increment_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "increment",
                    models.ForeignKey(
                        blank=True,
                        db_column="increment_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_records",
                        to="coreapp.salaryincrement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Increment History",
                "verbose_name_plural": "Salary Increment Histories",
                "ordering": ["-changed_at"],
            },
        ),
    ]
