# Generated by Django 4.2.27 on 2026-06-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coreapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="holiday",
            options={"ordering": ["date"]},
        ),
    ]
