"""Grouped serializers for the core app."""

from .auth_serializers import OfficeSerializer, DepartmentSerializer, DesignationSerializer, CustomUserSerializer, CustomUserListSerializer, EmployeeSelfSerializer, ManagerEmployeeListSerializer, HREmployeeDetailSerializer, AdminEmployeeDetailSerializer, EmployeeStatusAuditLogSerializer, BiometricAssignmentHistorySerializer, PasswordChangeHistorySerializer, UserRegistrationSerializer, UserLoginSerializer, LoginUserResponseSerializer, LightweightUserSummarySerializer, UserProfileSerializer, PasswordChangeSerializer
from .attendance_serializers import DeviceSerializer, AttendanceSerializer, AttendanceCreateSerializer, AttendanceLogSerializer, ESSLAttendanceLogSerializer, DuplicatePunchAttemptSerializer, UnmatchedBiometricPunchSerializer, AttendanceAuditLogSerializer, WorkingHoursSettingsSerializer, ESSLDeviceSyncSerializer, MonthlyAttendanceReportSerializer, DashboardStatsSerializer, OfficeStatsSerializer, AttendanceReportSerializer, BulkAttendanceSerializer, DeviceSyncSerializer
from .leave_serializers import LeaveSerializer, LeaveListSerializer, LeaveCreateSerializer, LeaveApprovalSerializer
from .document_serializers import DocumentSerializer, DocumentListSerializer, DocumentCreateSerializer, DocumentTemplateSerializer, GeneratedDocumentSerializer, GeneratedDocumentListSerializer, DocumentGenerationSerializer
from .notification_serializers import NotificationSerializer, NotificationListSerializer, SystemSettingsSerializer
from .resignation_serializers import ResignationSerializer, ResignationCreateSerializer, ResignationAdminUpdateSerializer, ResignationApprovalSerializer
from .device_serializers import DeviceUserSerializer, DeviceUserCreateSerializer, DeviceUserMappingSerializer, DeviceUserBulkCreateSerializer
from .salary_serializers import SalarySerializer, SalaryListSerializer, PayrollAdminSerializer, SalaryCreateSerializer, SalaryUpdateSerializer, SalaryApprovalSerializer, SalaryPaymentSerializer, SalaryTemplateSerializer, SalaryTemplateCreateSerializer, SalaryBulkCreateSerializer, SalaryReportSerializer, SalarySummarySerializer, SalaryAutoCalculateSerializer
from .shift_serializers import ShiftSerializer, EmployeeShiftAssignmentSerializer

__all__ = [
    'OfficeSerializer',
    'DepartmentSerializer',
    'DesignationSerializer',
    'CustomUserSerializer',
    'CustomUserListSerializer',
    'EmployeeSelfSerializer',
    'ManagerEmployeeListSerializer',
    'HREmployeeDetailSerializer',
    'AdminEmployeeDetailSerializer',
    'EmployeeStatusAuditLogSerializer',
    'BiometricAssignmentHistorySerializer',
    'PasswordChangeHistorySerializer',
    'UserRegistrationSerializer',
    'UserLoginSerializer',
    'LoginUserResponseSerializer',
    'LightweightUserSummarySerializer',
    'UserProfileSerializer',
    'PasswordChangeSerializer',
    'DeviceSerializer',
    'AttendanceSerializer',
    'AttendanceCreateSerializer',
    'AttendanceLogSerializer',
    'ESSLAttendanceLogSerializer',
    'DuplicatePunchAttemptSerializer',
    'UnmatchedBiometricPunchSerializer',
    'AttendanceAuditLogSerializer',
    'WorkingHoursSettingsSerializer',
    'ESSLDeviceSyncSerializer',
    'MonthlyAttendanceReportSerializer',
    'DashboardStatsSerializer',
    'OfficeStatsSerializer',
    'AttendanceReportSerializer',
    'BulkAttendanceSerializer',
    'DeviceSyncSerializer',
    'LeaveSerializer',
    'LeaveListSerializer',
    'LeaveCreateSerializer',
    'LeaveApprovalSerializer',
    'DocumentSerializer',
    'DocumentListSerializer',
    'DocumentCreateSerializer',
    'DocumentTemplateSerializer',
    'GeneratedDocumentSerializer',
    'GeneratedDocumentListSerializer',
    'DocumentGenerationSerializer',
    'NotificationSerializer',
    'NotificationListSerializer',
    'SystemSettingsSerializer',
    'ResignationSerializer',
    'ResignationCreateSerializer',
    'ResignationAdminUpdateSerializer',
    'ResignationApprovalSerializer',
    'DeviceUserSerializer',
    'DeviceUserCreateSerializer',
    'DeviceUserMappingSerializer',
    'DeviceUserBulkCreateSerializer',
    'SalarySerializer',
    'SalaryListSerializer',
    'PayrollAdminSerializer',
    'SalaryCreateSerializer',
    'SalaryUpdateSerializer',
    'SalaryApprovalSerializer',
    'SalaryPaymentSerializer',
    'SalaryTemplateSerializer',
    'SalaryTemplateCreateSerializer',
    'SalaryBulkCreateSerializer',
    'SalaryReportSerializer',
    'SalarySummarySerializer',
    'SalaryAutoCalculateSerializer',
    'ShiftSerializer',
    'EmployeeShiftAssignmentSerializer',
]
